# Generated by Django 6.0 on 2026-03-27 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
    ]
